name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  alert:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.jw5v5uqnzaxl3373w2kh2nvkgoog4f6zi6dzleomekpyq3dvjbzq }}" 
          github_token: "${{ secrets. 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 }}" 
          ado_organization: "eng18cs0252shailendrabilar"
          ado_project: "ADO-TESTING"
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
          log_level: 100
